"use client"
import { useState, useEffect } from "react"
import Loader from "@/app/components/Loader"

function privacypolicy() {
  const [loading, setloading] = useState(true);

useEffect (() => {
  setTimeout(() => setloading(false), 500);
}, []);

  return (
    <>
    {
      loading ? (
        <Loader /> ) : (
    
    <div className="container pt-20 pb-20">
      <h1 className='py-5 mt-14'>Privacy Policy </h1> <p>BluOne Ink is an electronic record in terms of the Information Technology Act, 2000 of the Republic of India and rules thereunder, as applicable, and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures to make the terms of this policy binding.</p>
      <p>At BluOne Ink, data protection is a matter of trust, and your privacy is very important to us. We use your personal information only in the manner set out in this Privacy Policy. Please read this Privacy Policy to learn more about our information gathering and dissemination practices.</p>
      <p>The privacy practices of this statement apply to our services available under the domain and subdomains of<a href="https://bluone.ink" data-wpel-link="internal"> </a><a href="https://bluone.ink" data-wpel-link="internal">https://bluone.ink</a> and apply generally to our parent, affiliates, subsidiaries, or joint venture websites. By visiting the Site, you agree to be bound by the terms and conditions of this Privacy Policy.</p><p>This Privacy Policy explains how BluOne Ink gathers personal information, classified as mandatory or optional as part of the normal operation of our services; and uses, discloses, and protects such information through the Site. This detailed Privacy Policy enables you to make informed decisions in dealings with us.</p>
      <p>By registering with BluOne Ink, you acknowledge your acceptance of the terms of this Privacy Policy, expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy, and agree that any personal information provided by you through BluOne Ink is provided under a lawful contract. This Privacy Policy is incorporated into and subject to the terms of the User Agreement.</p>
      <h6><strong>Changes to the Privacy Policy</strong></h6>
      <p>As our Site continues to develop, we may add new services and features. In the event that these additions affect our Privacy Policy, or if other changes in our privacy practices or applicable laws necessitate changes to the Privacy Policy, this document will be updated accordingly. If we make a material change in the way we use your personal information, we will provide prominent notice of the change on the Site. We will not, however, materially change our policies and practices to make them less protective of personal information we have previously collected from you without your express consent.</p><p>By using our Site, you are accepting the practices described in this Privacy Policy. If you do not agree to the terms of this Privacy Policy, please do not use the Site. We reserve the right to modify or amend the terms of our Privacy Policy from time to time without notice. All changes will become effective 24 hours after posting, and your continued use of the Site following the posting of changes to these terms of use will mean you accept those changes.</p>
      <p>The Privacy Policy only extends to the information you provide to us or the information otherwise collected by us through your usage of the Site (see Terms of Use), and does not extend to information procured through other mediums such as phone, postal service, book exhibitions, promotional events, etc.</p>
      <h6><strong>Information We Collect</strong></h6>
      <p>We collect two basic types of information from you in conjunction with your use of the Site:</p>
      <ul className="list-disc px-5 pb-5">
        <li className=''><strong>Personal information</strong>, which exclusively identifies you (e.g., your name, email address, telephone number, postal address, credit card information, etc.).</li>
        <li><strong>Non-personal information</strong>, which does not exclusively identify you but is related to you nonetheless (e.g., information about your interests, demographics, use of the Site).</li></ul>
      <p>We collect this information in the following ways:</p>
      <h6><strong>Directly Provided Information</strong></h6><p>We may ask you to provide your personal information, demographic information, or information about your preferences or interests when you:</p>
      <ul className="list-disc px-5 pb-5"><li>Register for an account on the Site.</li>
        <li>Sign up to receive email newsletters from us.</li>
        <li>Make a purchase on the Site.</li>
        <li>Enter a contest or sweepstakes.</li>
        <li>Participate in surveys or special promotions.</li>
        <li>Participate in social media accounts involving our authors, books, or brands.</li>
        <li>Participate in communities or forums on the Site.</li>
        <li>Submit user-generated content on any part of the Site that permits it.</li>
        <li>Knowingly volunteer information on any other part of the Site (e.g., request for customer service, submit a job application).</li></ul>
      <h6><strong>Information Collected by Us</strong></h6>
      <p>In addition to any information you provide directly to us, we and our third-party service providers may use a variety of technologies that automatically collect certain non-personal information when you interact with the Site or emails sent to you, including the following:</p>
      <ul className="px-5 pb-5 list-disc"><li><strong>Device Information:</strong> We may collect certain information about the computer or devices you use to access the Site, including IP address, geolocation information, unique device identifiers, browser type, browser language, and other transactional information.</li>
        <li><strong>Usage Information:</strong> We may log certain information about your use of the Site (e.g., log files, clickstream data, reading history of pages you view, search terms and search results) and additional “traffic data” (e.g., time of access, date of access, software crash reports, session identification number, access times, referring website addresses).</li>
        <li><strong>Location Information:</strong> Some of our applications may deliver content based on your current location if you choose to enable that feature of the app. If you enable the location-based feature, your current location will be stored locally on your device, which will then be used by the app. If you elect to have a location-based search saved to your history, we will store that information on our servers. If you do not enable the location-based service, or if an app does not have that feature, the app will not transmit to us, and we will not collect or store location information.</li>
        <li><strong>Cookies, Flash Cookies, and Web Beacons:</strong> Like many websites, we use cookies, flash cookies, web beacons, or similar technologies. “Cookies” are small text files stored on your computer or other devices when you visit certain online pages that record your preferences and actions. We use cookies for a variety of purposes, including remembering you and your preferences, tracking your use of our Site, and facilitating your payment transactions. Most web browsers automatically accept cookies, but, if you prefer, you can usually modify your browser setting to decline cookies. However, please note that refusing a cookie may limit your access to the Site.</li>
        <li><strong>Targeted Advertising:</strong> We may allow third parties to use cookies, web beacons, and similar technologies to better understand your behavior and browsing activities so that we can serve you targeted advertising while you are on our Site and display our ads to you when you visit other third-party sites. For example, we work with third-party network advertisers who may use these technologies to better provide advertisements about goods and services that may interest you. We do not control these third-party technologies, and they are not subject to this Privacy Policy. We do not authorize these third-party network advertisers to use this technology to collect personal information about you, and they do not have access to your personal information from us. They may, however, track your Internet usage anonymously (that is, without being able to identify you personally) over time and across other websites in their networks beyond our Site.</li></ul>
      <h6><strong>Security of Your Personal Information</strong></h6>
      <p>BluOne Ink takes reasonable steps to help protect and secure your personal information. However, please remember that no data storage or data transmission over the Internet, or by other means, can be guaranteed to be 100% secure. Thus, BluOne Ink cannot ensure or warrant the security of any information you transmit to us. Therefore, you understand, acknowledge, and agree that you transmit your personal information to our Site at your own risk.</p>
      <h6><strong>Third-Party Content and Links to Third-Party Websites</strong></h6>
      <p>Our Site may contain content hosted or served by third parties or links to websites operated by affiliates of BluOne Ink or third parties. Please be advised that the practices described in this Privacy Policy for BluOne Ink do not apply to information gathered by these third parties. We are not responsible for the actions and privacy policies employed by any third party, and our hosting of third-party content or linking to third-party websites does not constitute an endorsement of the content or business practices of those third parties.</p>
      <h6><strong>Public Areas, Forums, Reviews, and Community Areas</strong></h6>
      <p>Please remember that any information you share in public areas, such as forums, message boards, or feedback sections, becomes public, and anyone may take and use that information. Please be careful about what you disclose and do not post any personal information that you expect to keep private. Please consult our Terms of Use and the applicable guidelines, if any, for use of our forums and other community areas for more information.</p>
      <h6><strong>Governing Law</strong></h6>
      <p>This Site is published by BluOne Ink Pvt. Ltd. and is governed by all laws applicable within the territory of India, including the Information Technology (Amendment) Act, 2008 and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011. By using the Site, you agree to the terms of this Privacy Policy and consent to the exclusive jurisdiction and venue of courts in New Delhi, India, in all disputes arising out of or relating to the use of the Site or the Privacy Policy. Disputes may be referred to arbitration at the choice of BluOne Ink only, which shall then be governed as per the Arbitration and Conciliation Act, 1996.</p>
      <h6><strong>Assignment</strong></h6><p>We may change our ownership or corporate organization while providing the Site. We may also sell certain assets associated with the Site. As a result, please be aware that we may transfer some or all your information to a company acquiring all or part of our assets or to another company with which we have merged. Under such circumstances, we would, to the extent possible, require the acquiring party to follow the practices described in this Privacy Policy, as it may be amended from time to time. Nevertheless, we cannot ensure that an acquiring company or the merged company will have the same privacy practices or treat your information the same as described in this Privacy Policy.</p>
      <h6><strong>Notice to Non-India Users</strong></h6><p>If you are located outside India, you should be aware that your personally identifiable information will be transferred to India, the laws of which may be deemed by your country to have inadequate data protection. If you are located in a country outside India and voluntarily submit personally identifiable information to us on the Site, you thereby consent to the general use of such information as provided in this Privacy Policy and to the transfer and storage of that information in India.</p>
      <h6><strong>How to Opt-Out or Correct Your Information</strong></h6><p>You may always opt out of receiving future commercial emails and newsletters from BluOne Ink. We provide you with the opportunity to opt out of receiving such communications from us by clicking on the “unsubscribe” link within the email you receive. Please note that your request not to receive unsolicited commercial emails from us will not apply to messages that you request or that are not commercial in nature. For example, we may contact you concerning any purchases you have made with us, even if you opt out of receiving unsolicited commercial messages.</p>
      <h6><strong>How to Contact Us</strong></h6><p>If you have any questions about this Privacy Policy, you may write to us at editors@bluone.ink.</p>
    </div>
    )};
    </>
  )
}

export default privacypolicy
