import { AuthorsList } from "./allAuthorList";
export const BooksList = [
  {
    id: 1,
    slug:"sri-aurobindo-and-the-literary-renaissance-of-india",
    title: "Sri Aurobindo and The Literary Renaissance of India",
    publish_year: 2021,
    author: "Pariksith Singh, MD",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/sri-aurobindo-and-the-literary-renaissance-of-india/sri-aurobindo-and-the-literary-renaissance-of-india_cover.jpg",
  },
  {
    id: 2,
    title: "Design: A Business Case (Paperback)",  
    slug:"design-a-bussiness-case-paperback",
    publish_year: 2021,
    price: 795,
    author: "Brigitte Borja de Mozota/Amland",
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/design-a-bussiness-case-pb/design-a-bussiness-case_cover.jpg",
  },
  {
    id: 3,
    title: "Design: A Business Case (Hardback)",  
    slug:"design-a-bussiness-case-hardback",
    publish_year: 2021,
    author: "Brigitte Borja de Mozota/Amland",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/design-a-bussiness-case-hb/design-a-bussiness-case_cover.jpg",    
  },
  {
    id: 4,
    title: "Once Upon a Time in RIMC",  
    slug:"once-upon-a-time-in-rimc",
    publish_year: 2021,
    author: "Brigadier Jasbir Singh, SM",
    price: 250,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/once-upon-a-time-in-rimc/once-upon-a-time-in-rimc_cover.jpg",    
  },
  {
    id: 5,
    title: "Integral Education Beyond Schooling",
    slug:"integral-education-beyond-schooling",
    publish_year: 2021,
    author: "PARTHO",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/integral-education-beyond-schooling/integral-education-beyond-schooling_cover.jpg",
  },
  {
    id: 6,
    title: "The Fighting Fourth - A Personal Narrative Of The History Of 4 Kumaon",  
    slug:"the-fighting-fourth-a-personal-narrative-of-the-history-of-4-kumaon",
    publish_year: 2021,
    author: "Brig Jasbir Singh, SM",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-fighting-fourth/the-fighting-fourth_cover.jpg",
  },
  {
    id: 7,
    title: "War Despatches 1971",
    slug:"war-despatches1971",
    publish_year: 2021,
    author: "Brig B.S. Mehta",
    price: 899,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/war-despatches1971/war-despatches1971_cover.jpg",
  },
  {
    id: 8,
    title: "Seeing With Hands: How Chlildren Use Drawing To Make Sense Of The World",
    slug:"seeing-with-hands-how-children-use-drawing-to-make-sense-of-the-world",
    publish_year: 2021,
    author: "Jinan K.B.",
    price: 1195,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/seeing-with-hands/seeing-with-hands_cover.jpg",
  },
  {
    id: 9,
    title: "March To Justice: Global Military Law Landmarks",  
    slug:"march-to-justice-global-military-law-landmarks",
    publish_year: 2021,
    author: "Navdeep Singh",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/march-to-justice/march-to-justice_cover.jpg",
  },
  {
    id: 10,
    title: "Somewhere Among The Stars: Recollections of a Mystic (Paperback)",  
    slug:"somewhere-among-the-stars-recollections-of-a-mystic-pb",
    publish_year: 2022,
    author: "Adi Varuni",
    price: 395,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/somewhere-among-the-stars-pb/somewhere-among-the-stars_cover.jpg",
  },
  {
    id: 11,
    title: "Somewhere Among The Stars: Recollections of a Mystic (Hardback)",  
    slug: "somewhere-among-the-stars-recollections-of-a-mystic-hb",  
    publish_year: 2022,
    author: "Adi Varuni",
    price: 750,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/somewhere-among-the-stars-hb/somewhere-among-the-stars_cover.jpg",
  },
  {
    id: 12,
    title: "Identity's Last Secret",
    slug: "identitys-last-secret",  
    publish_year: 2022,
    author: "Dr. Makarand R. Paranjape",
    price: 1495,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/identitys-last-secret/identitys-last-secret_cover.png",

  },
  {
    id: 13,
    title: "The Eternal Feminine",
    slug: "the-eternal-feminine",  
    publish_year: 2022,
    author: "Dr. Alok Pandey",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-eternal-feminine/the-eternal-feminine_cover.jpg",
  },
  {
    id: 14,
    title: "Hop's Spectacular Adventure",  
    slug: "hops-spectacular-adventure",
    publish_year: 2022,
    author: "ZAIN HASHMY",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hops-spectacular-adventure/hops-spectacular-adventure_cover.png",
  },
  {
    id: 15,
    title: "How the Rainbow Got Its Colour",  
    slug: "how-the-rainbow-got-its-colour",
    publish_year: 2022,
    author: "Gaatha Shakti",
    price: 299,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/how-the-rainbow-got-its-colour/how-the-rainbow-got-its-colour_cover.jpg",
  },
  {
    id: 16,
    title: "Confidence Cures : The Art Of Self-Wellness",
    slug: "confidence-cures-the-art-of-self-wellness",
    publish_year: 2022,
    author: "Lt.Gen.S.B.Sehajpal / Mrs. Kiran Sehajpal",
    price: 495,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/confidence-cures/confidence-cures_cover.jpg",
  },
  {
    id: 17,
    title: "Sri Aurobindo and Philosophy Hardback",  
    slug: "sri-aurobindo-and-philosophy-hardback",
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/sri-aurobindo-and-philosophy-hb/sri-aurobindo-and-philosophy-hb_cover.jpg",
  },
  {
    id: 18,
    title: "Sri Aurobindo And Philosophy (Paperback)",  
    slug: "sri-aurobindo-and-philosophy-paperback",
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 595,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/sri-aurobindo-and-philosophy-pb/sri-aurobindo-and-philosophy-pb_cover.jpg",
  },
  {
    id: 19,
    title: "Snakes in The Ganga: Breaking India 2.0",
    slug: "snakes-in-the-ganga-breaking-india-2.0",  
    publish_year: 2022,
    author: "Rajiv Malhotra, Vijaya Viswanathan",
    price: 895,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/snakes-in-the-ganga/Snakes-in-the-Ganga-Breaking-India-2.0-front-cover.jpg",
  },
  {
    id: 20,
    title: "The Eternal Gene And Other Tales Of Malaise",
    slug: "the-eternal-gene-and-other-tales-of-malaisa",  
    publish_year: 2022,
    author: "Ankush Singh Thorpe",
    price: 495,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-eternal-gene/the-eternal-gene_cover.jpg",
  },
  {
    id: 21,
    title: "This Is Sanatan Dharma: The Quest For Truth",
    slug: "this-is-sanatan-dharma-the-quest-for-truth",  
    publish_year: 2022,
    author: "Partho",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/this-is-sanatan-dharma/this-is-sanatan-dharma_cover.jpg",
  },
  {
    id: 22,
    title: "Chutti Ke Din",  
    slug: "chutti-ke-din", 
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/chutti-ke-din-hindi-poetry/chutti-ke-din-hindi-poetry_cover.jpg",
  },
  {
    id: 23,
    title: "Jana Awjanar Majhe (Paperback)",
    slug: "jana-awjanar-majhe-paperback", 
    publish_year: 2022,
    author: "Bimal Chakravarty",
    price: 195,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/jana-awjanar-majhe-pb/jana-awjanar-majhe-pb_cover.jpg",
  },
  {
    id: 24,
    title: "Jana Awjanar Majhe (Hardback)",
    slug: "jana-awjanar-majhe-hardback",
    publish_year: 2022,
    author: "Bimal Chakravarty",
    price: 695,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/jana-awjanar-majhe-hb/jana-awjanar-majhe-hb_cover.jpg",
  },
  {
    id: 25,
    title: "Swayam Se Parichay",
    slug: "swayam-se-parichay",
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 195,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/swayam-se-parichay/swayam-se-parichay_cover.jpg",
  },
  {
    id: 26,
    title: "Swayam Ka Ghuspaithiya",
    slug: "swayam-ka-ghuspaithiya",
    publish_year: 2023,
    author: "Pariksith Singh",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/swayam-ka-ghuspaithiya/swayam-ka-ghuspaithiya_cover.jpg",
  },
  // {
  //   id: 27,
  //   title: "There Was a Girl I Loved Once",  
  //   slug: "there-was-a-girl-i-loved-once",
  //   publish_year: 2022,
  //   author: "Pariksith Singh",
  //   price: 350,
  //   book_image: "https://bluone-ink.s3.amazonaws.com/images/books/there-was-a-girl-i-loved-once/there-was-a-girl-i-loved-once_cover.jpg",
  // },
  {
    id: 28,
    title: "Hindutva : Origin Evolution and Future",
    slug: "hindutva-origin-evolution-and-future",
    publish_year: 2022,
    author: "Aravindan Neelakandan",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hindutva-origin-evolution-and-future/hindutva-origin-evolution-and-future_cover.jpg",
  },
  {
    id: 29,
    title: "Life Of An Industani: Six Degress Of Separation",  
    slug: "life-of-an-industani-six-degress-of-separation", 
    publish_year: 2022,
    author: "Shiv Kunal Verma",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/life-of-an-industani/life-of-an-industani_cover.jpg",
  },
  {
    id: 30,
    title: "All Stray Dogs Go to Heaven",  
    slug: "all-stray-dogs-go-to-heaven",
    publish_year: 2023,
    author: "Krishna Candeth",
    price: 695,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/all-stray-dogs-go-to-heaven-pb/all-stray-dogs-go-to-heaven-pb_cover.jpg",
  },
  {
    id: 31,
    title: "Grit to Glory",  
    slug: "grit-to-glory", 
    publish_year: 2022,
    author: "Brig B.S. Mehta",
    price: 895,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/grit-to-glory/grit-to-glory_cover.jpg",
  },
  {
    id: 32,
    title: "Bharat Ke Janjaatiya Krantiveer: Swatantrata Sangram Ki 75 Unsuni Kahaniyaan (Paperback)",  
    slug: "bharat-ke-janjaatiya-krantiveer-swatantrata-sangram-ki-75-unsuni-kahaniyaan-pb", 
    publish_year: 2023,
    author: "Dhaval Patel",
    price: 395,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/bharat-ke-janjatiya-krantiveer-pb/bharat-ke-janjatiya-krantiveer-pb_cover.jpg",
  },
  {
    id: 33,
    title: "Bharat Ke Janjaatiya Krantiveer: Swatantrata Sangram Ki 75 Unsuni Kahaniyaan (Hardback)",  
    slug: "bharat-ke-janjaatiya-krantiveer-swatantrata-sangram-ki-75-unsuni-kahaniyaan-hb",
    publish_year: 2023,
    author: "Dhaval Patel",
    price: 695,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/bharat-ke-janjatiya-krantiveer-hb/bharat-ke-janjatiya-krantiveer-hb_cover.jpg",
  },
  {
    id: 34,
    title: "Battle For Iits : A Defense Of Meritocracy",
    slug: "battle-for-iits-a-defence-of-meritocracy",
    publish_year: 2023,
    author: "Rajiv Malhotra, Vijaya Viswanathan",
    price: 250,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-battle-for-iits/the-battle-for-iits_cover.jpg",
  },
  {
    id: 35,
    title: "Varna Jati Caste: A Primer On Indian Social Structure",
    slug: "varna-jati-caste-a-primer-on-indian-social-structure", 
    publish_year: 2023,
    author: "Rajiv Malhotra, Vijaya Viswanathan",
    price: 250,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/varna-jati-caste/varna-jati-caste_cover.jpg",
  },
  {
    id: 36,
    title: "The Power Of Future Machines: Essays On Artificial Intelligence",
    slug: "the-power-of-future-machines-essays-on-artificial-intelligence",  
    publish_year: 2023,
    author: ["Rajiv Malhotra", "T. N. Sudarshan" ,"Manogna Sastry"],
    price: 750,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-power-of-future-machines/the-power-of-future-machines_cover.jpg",
  },
  {
    id: 37,
    title: "Of Newtons And Apples: Insights Into 50 Great Minds In Human History",  
    slug: "of-newtons-and-apples-insights-into-50-great-minds-in-human-history",  
    publish_year: 2023,
    author: "ABHISHEK KUMAR",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/of-newtons-and-apples/of-newtons-and-apples_cover.jpg",
  },
  {
    id: 38,
    title: "Probasir Golpo (Bengali)",  
    slug: "probasir-golpo-bengali",  
    publish_year: 2023,
    author: "Bimal Chakravarty",
    price: 250,
    book_image: "https://m.media-amazon.com/images/I/71YHfXm0XwL._SY466_.jpg",
  },
  {
    id: 39,
    title: "Symbols and Parables",  
    slug: "symbols-and-parables",  
    publish_year: 2023,
    author: "Dr. Alok Pandey",
    price: 295,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/symbols-and-parables/symbols-and-parables_cover.jpg",
  },
  {
    id: 40,
    title: "Adyatmikta: Explorations Into Hindu Spiritual Practices",
    slug: "adhyatmikta-explorations-into-hindu-spiritual-practices",  
    publish_year: 2023,
    author: "Rajarshi Ranjan Nandy",
    price: 495,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/adyatmikta/adhyatmikta_cover.jpg",
  },
  {
    id: 41,
    title: "Building Beyond Infra: The Evolution Of The Construction Industry",
    slug: "building-beyond-infra-the-evolution-of-the-construction-industry",  
    publish_year: 2023,
    author: "Akhilesh Srivastava",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/building-beyond-infra/building-beyond-infra_cover.jpeg",
  },
  {
    id: 42,
    title: "Purvyam: Before The Beginning",  
    slug: "purvyam-before-the-beginning",  
    publish_year: 2023,
    author: "Abhishek Talwar",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/purvyam/purvyam_cover.jpeg",
  },
  {
    id: 43,
    title: "Completing Vyasa’s Mahabharta",
    slug: "completing-vyasas-mahabharta", 
    publish_year: 2023,
    author: "Abhinav Agarwal",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/completing-vyasas-mahabharta/completing-vyasas-mahabharta_cover.jpg",
  },
  {
    id: 44,
    title: "Hindus In Hindu Rashtra: Eighth-Class Citizens And Victims Of State-Sanctioned Apartheid",  
    slug: "hindus-in-hindu-rashtra-eighth-class-citizens-and-victims-of-state-sanctioned-apartheid",  
    publish_year: 2023,
    author: "Anand Ranganathan",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hindus-in-hindu-rashtra-eng/hindus-in-hindu-rashtra-eng_cover.jpg",
  },
  {
    id: 45,
    title: "Invaders And Infidels: The Khalji Devastation Of Infidel Devagiri (Book 2)",  
    slug: "invaders-and-infidels-the-khalji-devastation-of-infidel-devagiri-book-2", 
    publish_year: 2023,
    author: "Sandeep Balakrishna",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/invaders-and-infidels-book-2/invaders-and-infidels-book-2_cover.jpg",
  },
  {
    id: 46,
    title: "Sobha Singh Artist: Life And Legacy",  
    slug: "sobha-singh-artist-life-and-legacy",  
    publish_year: 2023,
    author: "Hirday Paul Singh",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/sobha-singh-artist/sobha-singh-artist_cover.jpg",
  },
  {
    id: 47,
    title: "The Never-Dying Fire: The Life And Thought Of Sri Aurobindo",
    slug: "the-never-dying-fire-the-life-and-thought-of-sri-aurobindo",  
    publish_year: 2023,
    author: "Luc Venet",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-never-dying-fire/the-never-dying-fire_cover.jpg",
  },
  {
    id: 48,
    title: "The Veda Made Simple",
    slug: "the-veda-made-simple",  
    publish_year: 2023,
    author: "Dr. Pariksith Singh",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-veda-made-simple/the-veda-made-simple_cover.jpg",
  },
  {
    id: 49,
    title: "Modi Ka Banaras",  
    slug: "modi-ka-banaras",  
    publish_year: 2023,
    author: "Arvind Chaturvedi",
    price: 449,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/modi-ka-banaras/modi-ka-banaras_cover.jpg",
  },
  {
    id: 50,
    title: "India And The Changing World Order: Merging Paradigm Shift In The Changing Global, Political And Economic Order",
    slug: "india-and-the-changing-world-order-merging-paradigm-shift-in-the-changing-global-political-and-economic-order",  
    publish_year: 2023,
    author: "S. Gurumurthy",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/india-and-the-changing-world-order/india-and-the-changing-world-order_cover.jpg",
  },
  {
    id: 51,
    title: "Gods Dancing Among Men: The Mystical World Of Theyyams Of North Malabar",
    slug: "gods-dancing-among-men-the-mystical-world-of-theyyams-of-north-malabar",  
    publish_year: 2023,
    author: "PUSHPA KURUP",
    price: 1999,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/gods-dancing-among-men/gods-dancing-among-men_cover.jpg",
  },
  {
    id: 52,
    title: "Arc Of Governance: The Flavour Of New India",
    slug: "arc-of-governance-the-flavour-of-new-india",  
    publish_year: 2023,
    author: "M.G. Devasahayam",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/arc-of-governance/arc-of-governance_cover.jpg",
  },
  {
    id: 53,
    title: "Hindus in Hindu Rashtra (Hindi)",  
    slug: "hindus-in-hindu-rashtra-hindi",  
    publish_year: 2023,
    author: "Anand Ranganathan",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hindus-in-hindu-rashtra-hindi/hindus-in-hindu-rashtra-hindi_cover.jpg",
  },
  {
    id: 54,
    title: "Hindus in Hindu Rashtra (Marathi)",  
    slug: "hindus-in-hindu-rashtra-marathi",
    publish_year: 2023,
    author: "Anand Ranganathan",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hindus-in-hindu-rashtra-marathi/hindus-in-hindu-rashtra-marathi_cover.jpg",
  },
  {
    id: 55,
    title: "The Vaccine War",
    slug: "the-vaccine-war", 
    publish_year: 2023,
    author: "Vivek Ranjan Agnihotri",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-vaccine-war/the-vaccine-war_cover.jpg",
  },
  {
    id: 56,
    title: "Ram Janmabhoomi: The Inspiration For Hindu Resurgence",
    slug: "ram-janmabhoomi-the-inspiration-for-hindu-resurgenc",  
    publish_year: 2023,
    author: "Rashmi Samant",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/ram-janmabhoomi/ram-janmabhoomi_cover.jpg",
  },
  {
    id: 57,
    title: "Modi'S Governance Triumph: Reshaping India's Path To Prosperity",
    slug: "modis-governance-triumph-reshaping-indias-path-to-prosperity",  
    publish_year: 2024,
    author: "Tarun Chugh",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/modis-governance-triump/modis-governance-triump_cover.jpg",
  },
  {
    id: 58,
    title: "Compulsive NosePicking and Other True Tales",
    slug: "compulsive-nosepicking-and-other-true-tales",  
    publish_year: 2023,
    author: "Anil Maheshwari",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/compulsive-nose-picking-and-other-true-tales/compulsive-nose-picking-and-other-true-tales_cover.jpg",
  },
  {
    id: 59,
    title: "Waiting For Shiva: Unearthing The Truth Of Kashi’S Gyan Vapi",
    slug: "waiting-for-shiva-unearthing-the-truth-of-kashis-gyan-vapi",  
    publish_year: 2024,
    author: "Vikram Sampath",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/waiting-for-shiva/waiting-for-shiva_cover.jpg",
  },
  {
    id: 60,
    title: "Snakes In The Ganga: Breaking India 2.0 (Paperback)",  
    slug: "snakes-in-the-ganga-breaking-india-2.0-pb",  
    publish_year: 2022,
    author: "Rajiv Malhotra",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/snakes-in-the-ganga/snakes-in-the-ganga_cover.jpg",
  },
  {
    id: 61,
    title: "Modian Consensus: The Rediscovery Of Bharat",
    slug: "modian-consensus-the-rediscovery-of-bharat",  
    publish_year: 2024,
    author: "Swadesh Singh",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/modian-consensus/modian-consensus_cover.jpg",
  },
  {
    id: 62,
    title: "Bharat Rising: Dharma, Democracy, Diplomacy",  
    slug: "bharat-rising-dharma-democracy-diplomacy",  
    publish_year: 2024,
    author: "Utpal Kumar",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/bharat-rising/bharat-rising_cover.jpg",
  },
  {
    id: 63,
    title: "Ram Janmabhoomi: The Inspiration For Hindu Resurgence (Hindi)",
    slug: "ram-janmabhoomi-the-inspiration-for-hindu-resurgence-hindi", 
    publish_year: 2024,
    author: "Rashmi Samant",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/ram-janmabhoomi-hindi/ram-janmabhoomi-hindi_cover.jpg",
  },
  {
    id: 64,
    title: "Whispers Of The Unseen: The Quest For Sixty-Four Yoginis",
    slug: "whispers-of-the-unseen-the-quest-for-sixty-four-yoginis", 
    publish_year: 2024,
    author: "S Beena Unikrishnan",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/whispers-of-the-unseen/whispers-of-the-unseen_cover.jpg",
  },
  {
    id: 65,
    title: "Adideva: 25 Legends Behind His 25 Names: A Yatra Through Puranas, Sthala Puranas And Itihasas",  
    slug: "adideva-25-legends-behind-his-25-names-a-yatra-through-puranas-sthala-puranas-and-itihasas",  
    publish_year: 2024,
    author: "DEEPA BHASKARAN SALEM",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/adideva/adideva_cover.jpg",
  },
  {
    id: 66,
    title: "Modi'S Governance Triumph: Reshaping India's Path To Prosperity (Hindi)",
    slug: "modis-governance-triumph-reshaping-indias-path-to-prosperity-hindi",  
    publish_year: 2024,
    author: "Tarun Chugh",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/modis-governance-triumph-hindi/modis-governance-triumph-hindi_cover.webp",
  },
  {
    id: 67,
    title: "Invaders And Infidels: The Khalji Devastation Of Infidel Devagiri (Book 1)",  
    slug: "invaders-and-infidels-the-khalji-devastation-of-infidel-devagiri-book-1",  
    publish_year: 2024,
    author: "Sandeep Balakrishna",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/invaders-and-infidels-book-1/invaders-and-infidels-book-1_cover.jpg",
  },
  {
    id: 68,
    title: "Nastik: Why I Am Not An Atheist",  
    slug: "nastik-why-i-am-not-an-atheist", 
    publish_year: 2024,
    author: "KUSHAL MEHRA",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/nastik/nastik_cover.jpg",
  },
  {
    id: 69,
    title: "Waiting For Shiva: Unearthing The Truth Of Kashi’S Gyan Vapi In Hindi ( प्रतीक्षा शिव की: ज्ञान वापी काशी के सत्य का उद्घाटन )",
    slug: "waiting-for-shiva-unearthing-the-truth-of-kashis-gyan-vapi-in-hindi", 
    publish_year: 2024,
    author: "Vikram Sampath",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/waiting-for-shiva-hindi/waiting-for-shiva-hindi_cover.jpg",
  },
  {
    id: 70,
    title: "Apostles : A Candid Take On Managing Organisations & Talent",  
    slug: "apostles-a-candid-take-on-managing-organisations-and-talent",  
    publish_year: 2024,
    author: "Biswaroop Mukherjee",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/apostles/apostles_cover.jpg",
  },
  {
    id: 71,
    title: "Devdoot",
    slug: "devdoot",  
    publish_year: 2024,
    author: "Aniruddh Rawat",
    price: 199,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/devdoot-hindi/devdoot-hindi_cover.jpg",
  },
  {
    id: 72,
    title: "Stalled Wheels of Justice",
    slug: "stalled-wheels-of-justice", 
    publish_year: 2024,
    author: "Shishir Tripathi",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/stalled-wheels-of-justice/stalled-wheels-of-justice_cover.jpg",
  },
  {
    id: 73,
    title: "Bangaliyana: Doodles, Cartoons And Musings From A Probashi Bengali",
    slug: "bangaliyana-doodles-cartoons-and-musings-from-a-probashi-bengali", 
    publish_year: 2024,
    author: "Rajeev Banerjee",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/bangaliyana/bangaliyana_cover.jpg",
  },
  {
    id: 74,
    title: "Waiting For Shiva: Unearthing The Truth Of Kashi'S Gyan Vapi (Marathi)",
    slug: "waiting-for-shiva-unearthing-the-truth-of-kashis-gyan-vapi-marathi", 
    publish_year: 2024,
    author: "Vikram Sampath",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/waiting-for-shiva-marathi/waiting-for-shiva-marathi_cover.jpg",
  },
  {
    id: 75,
    title: "Krishna-Niti: Timeless Strategic Wisdom",
    slug: "krishna-niti-timeless-strategic-wisdom",  
    publish_year: 2024,
    author: ["Kushagra Aniket", "Nityananda Misra"],
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/krishna-niti/krishna-niti_cover.jpg",
  },
  {
    id: 76,
    title: "Whispers From The Past: Art And Wisdom Of Kashmir",  
    slug: "whispers-from-the-past-art-and-wisdom-of-kashmir",  
    publish_year: 2024,
    author: "Subhash Kak",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/whispers-from-the-past/whispers-from-the-past_cover.jpg",
  },
  {
    id: 77,
    title: "Kashi: The Valiant History Of A Sacred Geography",  
    slug: "kashi-the-valiant-history-of-a-sacred-geography",  
    publish_year: 2024,
    author: "Aditi Banerjee",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/kashi/kashi_cover.jpg",
  },
  {
    id: 78,
    title: "My Freedom Of Expression: Reflections On Contemporary Issues",
    slug: "my-freedom-of-expression-reflections-on-contemporary-issues",  
    publish_year: 2024,
    author: "PARIMAL BRAHMA",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/my-freedom-of-expression/my-freedom-of-expression_cover.jpg",
  },
  {
    id: 79,
    title: "Shared Roots: Tales From The Indosphere",
    slug: "shared-roots-tales-from-the-indosphere", 
    publish_year: 2024,
    author: "Ratul Chakraborty",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/shared-roots/shared-roots_cover.jpg",
  },
  {
    id: 80,
    title: "Reclaiming Bharatavarsha",
    slug: "reclaiming-bharatavarsha", 
    publish_year: 2024,
    author: "Sandeep Balakrishna",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/reclaiming-bharatvarsha/reclaiming-bharatvarsha_cover.jpg",
  },
  {
    id: 81,
    title: "Rearming Hinduism: Nature, Hinduphobia, And The Return Of Indian Intelligence",  
    slug: "rearming-hinduism-nature-hinduphobia-and-the-return-of-indian-intelligence",  
    publish_year: 2024,
    author: "Vamsee Juluri",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/rearming-hinduism/rearming-hinduism_cover.jpg",
  },
  {
    id: 82,
    title: "Desires, Dreams And Powers: Reminiscences Of West Bengal And The Northeast",
    slug: "desire-dreams-and-powers-reminiscences-of-west-bengal-and-the-northeast",  
    publish_year: 2024,
    author: "TATHAGATA ROY",
    price: 899,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/desire-dreams-and-powers/desire-dreams-and-powers_cover.jpg",
  },
  {
    id: 83,
    title: "The Collector'S Mother: How An Underprivileged Woman Inspired Her Son To Become An Ias Officer",
    slug: "the-collectors-mother-how-an-underprivileged-woman-inspired-her-son-to-become-an-ias-officer",  
    publish_year: 2024,
    author: "Bishnupada Sethi",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-collectors-mother/the-collectors-mother_cover.jpg",
  },
  {
    id: 84,
    title: "How To Get Into IAS: A Perfect Guide To Crack Upsc Exam",  
    slug: "how-to-get-into-ias-a-perfect-guide-to-crack-upsc-exam",  
    publish_year: 2024,
    author: "Rohit Sharma & Shakti Singh (IRS)",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/how-to-get-into-ias/how-to-get-into-ias_cover.jpg",
  },
  {
    id: 85,
    title: "Decolonizing Hinduism: Exposing Shallow Attempts That Destroyed And Divided Dharma",
    slug: "decolonizing-hinduism-exposing-shallow-attempts-that-destroyed-and-divided-dharma",  
    publish_year: 2024,
    author: "Shubham G. Deore",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/decolonizing-hinduism/decolonizing-hinduism_cover.jpg",
  },
  {
    id: 86,
    title: "The Battle for Consciousness Theory: A Response to Ken Wilber's Hijacking of Sri Aurobindo and Other Indian Thought",  
    slug: "the-battle-for-consciousness-theory-a-response-to-ken-wilbers-hijacking-of-sri-aurobindo-and-other-indian-thought",  
    publish_year: 2024,
    author: ["Rajiv Malhotra", " Manogna Sastry", " Kundan Singh"],
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-battle-for-consciousness-theory-a-response-to-ken-wilbers-hijacking-of-sri-aurobindo-and-other-indian-thought/the-battle-for-consciousness-theory-a-response-to-ken-wilbers-hijacking-of-sri-aurobindo-and-other-indian-thought_cover.jpg",
  },
  {
    id: 87,
    title: "India in 2050: Visions for a Superpower India",
    slug: "india-in-2050-visions-for-a-superpower-india",
    publish_year: 2024,
    author: "Karan Mehrishi",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/india-in-2050-visions-for-a-superpower-india/india-in-2050-visions-for-a-superpower-india_cover.jpg",
  },
  {
    id: 88,
    title: "Being Hindu: A Political History From Aditya Chola To Narendra Modi",
    slug: "being-hindu-a-political-history-from-aditya-chola-to-narendra-modi", 
    publish_year: 2024,
    author: "Saumya Dey",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/being-hindu/being-hindu_cover.jpg",
  },
  {
    id: 89,
    title: "Waiting for Shiva (Telugu)",
    slug: "waiting-for-shiva-telugu",  
    publish_year: 2024,
    author: "Vikram Sampath",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/waiting-for-shiva-telugu/waiting-for-shiva-telugu_cover.jpg",
},
  {
    id: 90,
    title: "Genome To Om: Evolving Journey Of Modern Science To Meta-Science",
    slug: "genome-to-om-evolving-journey-of-modern-science-to-meta-science",  
    publish_year: 2024,
    author: ["Bhushan Patwardhan", "Indu Ramchandani"],
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/genome-to-om/genome-to-om_cover.jpg",
  },
  {
    id: 91,
    title: "The Number you are Calling is Switched off",  
    slug: "the-number-you-are-calling-is-switched-off",  
    publish_year: 2024,
    author: "Tushar Srivastava",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-number-you-are-calling-is-switched-off/the-number-you-are-calling-is-switched-off_cover.jpg",
  },
  {
    id: 92,
    title: "Crossing Continents: European Explorers and India's Mysteries",  
    slug: "crossing-continents-european-explorers-and-indias-mysteries",  
    publish_year: 2024,
    author: "Amit Agarwal",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/crossing-continents-european-explorers-and-indias-mysteries/crossing-continents-european-explorers-and-indias-mysteries_cover.jpg",
  },
  {
    id: 93,
    title: "From Partition to Progress: Persecuted Hindus and the Struggle for Citizenship",  
    slug: "from-partition-to-progress-persecuted-hindus-and-the-struggle-for-citizenship",  
    publish_year: 2024,
    author: "Anirban Ganguly",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/from-partition-to-progress-persecuted-hindus-and-the-struggle-for-citizenship/from-partition-to-progress-persecuted-hindus-and-the-struggle-for-citizenship_cover.jpg",
  },
  {
    id: 94,
    title: "India's New Right: Powering the Current Wave of Nationalism and Civilisational Revival",  
    slug: "indias-new-right-powering-the-current-wave-of-nationalism-and-civilisational-revival", 
    publish_year: 2024,
    author: "Abhijit Majumder",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/indias-new-right-powering-the-current-wave-of-nationalism-and-civilisational-revival/indias-new-right-powering-the-current-wave-of-nationalism-and-civilisational-revival_cover.jpg",
  },
  {
    id: 95,
    title: "A Dharmic Social History of India",
    slug: "a-dharmic-social-history-of-india",  
    publish_year: 2024,
    author: "Aravindan Neelakandan",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/a-dharmic-social-history-of-india/a-dharmic-social-history-of-india_cover.jpg",
  },
  {
    id: 96,
    title: "Padma Bharatis: Ordinary Indians, Extraordinary Triumphs",
    slug: "padma-bharatis-ordinary-indians-extraordinary-triumphs",
    publish_year: 2024,
    author: "Jay Jina",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/padma-bharatis/padma-bharatis_cover.jpg",
  },
  {
    id: 97,
    title: "Anjali Geetan Ri",
    slug: "anjali-geetan-ri",
    publish_year: 2022,
    author: "Ikram Rajasthani",
    price: "",
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/Anjali+Geetan+Ri/anjali-Geetan-Ri-front-cover.jpg",
  },
  ];