import { AuthorsList } from "./allAuthorList";
export const BooksList = [
  {
    id: 1,
    slug:"sri-aurobindo-and-the-literary-renaissance-of-india",
    title: "Sri Aurobindo and The Literary Renaissance of India",
    publish_year: 2021,
    author: "Pariksith Singh, MD",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/sri-aurobindo-and-the-literary-renaissance-of-india/sri-aurobindo-and-the-literary-renaissance-of-india_cover.jpg",
  },
  {
    id: 2,
    title: "Design a Business Case PB",  
    slug:"design-a-bussiness-case-pb",
    publish_year: 2021,
    price: 795,
    author: "Brigitte Borja de Mozota/Amland",
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/design-a-bussiness-case-pb/design-a-bussiness-case_cover.jpg",
  },
  {
    id: 3,
    title: "Design a Business Case HB",  
    slug:"design-a-bussiness-case-hb",
    publish_year: 2021,
    author: "Brigitte Borja de Mozota/Amland",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/design-a-bussiness-case-hb/design-a-bussiness-case_cover.jpg",    
  },
  {
    id: 4,
    title: "Once Upon a Time in RIMC",  
    slug:"once-upon-a-time-in-rimc",
    publish_year: 2021,
    author: "Brig Jasbir Singh, SM",
    price: 250,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/once-upon-a-time-in-rimc/once-upon-a-time-in-rimc_cover.jpg",    
  },
  {
    id: 5,
    title: "Integral Education Beyond Schooling",
    slug:"integral-education-beyond-schooling",
    publish_year: 2021,
    author: "PARTHO",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/integral-education-beyond-schooling/integral-education-beyond-schooling_cover.jpg",
  },
  {
    id: 6,
    title: "The Fighting Fourth",  
    slug:"the-fighting-fourth",
    publish_year: 2021,
    author: "Brig Jasbir Singh, SM",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-fighting-fourth/the-fighting-fourth_cover.jpg",
  },
  {
    id: 7,
    title: "War Despatches 1971",
    slug:"war-despatches1971",
    publish_year: 2022,
    author: "Brig B.S. Mehta",
    price: 899,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/war-despatches1971/war-despatches1971_cover.jpg",
  },
  {
    id: 8,
    title: "Seeing with Hands",
    slug:"seeing-with-hands",
    publish_year: 2021,
    author: "Jinan K.B.",
    price: 1195,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/seeing-with-hands/seeing-with-hands_cover.jpg",
  },
  {
    id: 9,
    title: "March to Justice",  
    slug:"march-to-justice",
    publish_year: 2022,
    author: "Navdeep Singh",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/march-to-justice/march-to-justice_cover.jpg",
  },
  {
    id: 10,
    title: "Somewhere Among the Stars PB",  
    slug:"somewhere-among-the-stars-pb",
    publish_year: 2022,
    author: "Adi Varuni",
    price: 395,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/somewhere-among-the-stars-pb/somewhere-among-the-stars_cover.jpg",
  },
  {
    id: 11,
    title: "Somewhere Among the Stars HB",  
    slug: "somewhere-among-the-stars-hb",  
    publish_year: 2022,
    author: "Adi Varuni",
    price: 750,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/somewhere-among-the-stars-hb/somewhere-among-the-stars_cover.jpg",
  },
  {
    id: 12,
    title: "Identity's Last Secret",
    slug: "identitys-last-secret",  
    publish_year: 2022,
    author: "Dr.Makarand R. Paranjape",
    price: 1495,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/identitys-last-secret/identitys-last-secret_cover.png",

  },
  {
    id: 13,
    title: "The Eternal Feminine",
    slug: "the-eternal-feminine",  
    publish_year: 2021,
    author: "Dr. Alok Pandey",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-eternal-feminine/the-eternal-feminine_cover.jpg",
  },
  {
    id: 14,
    title: "Hop's Spectacular Adventure",  
    slug: "hops-spectacular-adventure",
    publish_year: 2022,
    author: "ZAIN HASHMY",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hops-spectacular-adventure/hops-spectacular-adventure_cover.png",
  },
  {
    id: 15,
    title: "How the Rainbow Got Its Colour",  
    slug: "how-the-rainbow-got-its-colour",
    publish_year: 2022,
    author: "Gaatha Shakti",
    price: 299,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/how-the-rainbow-got-its-colour/how-the-rainbow-got-its-colour_cover.jpg",
  },
  {
    id: 16,
    title: "Confidence Cures",
    slug: "confidence-cures",
    publish_year: 2022,
    author: "Lt.Gen.S.B.Sehajpal / Mrs. Kiran Sehajpal",
    price: 495,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/confidence-cures/confidence-cures_cover.jpg",
  },
  {
    id: 17,
    title: "Sri Aurobindo and Philosophy HB",  
    slug: "sri-aurobindo-and-philosophy-hb",
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/sri-aurobindo-and-philosophy-hb/sri-aurobindo-and-philosophy-hb_cover.jpg",
  },
  {
    id: 18,
    title: "Sri Aurobindo and Philosophy PB",  
    slug: "sri-aurobindo-and-philosophy-pb",
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 595,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/sri-aurobindo-and-philosophy-pb/sri-aurobindo-and-philosophy-pb_cover.jpg",
  },
  {
    id: 19,
    title: "Snakes in the Ganga",
    slug: "snakes-in-the-ganga",  
    publish_year: 2022,
    author: "Rajiv Malhotra, Vijaya Viswanathan",
    price: 895,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/snakes-in-the-ganga/snakes-in-the-ganga_cover.jpg",
  },
  {
    id: 20,
    title: "The Eternal Gene",
    slug: "the-eternal-gene",  
    publish_year: 2022,
    author: "Ankush Singh Thorpe",
    price: 495,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-eternal-gene/the-eternal-gene_cover.jpg",
  },
  {
    id: 21,
    title: "This is Sanatan Dharma",
    slug: "this-is-sanatan-dharma",  
    publish_year: 2022,
    author: "Partho",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/this-is-sanatan-dharma/this-is-sanatan-dharma_cover.jpg",
  },
  {
    id: 22,
    title: "Chutti Ke Din - Hindi Poetry",  
    slug: "chutti-ke-din-hindi-poetry", 
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/chutti-ke-din-hindi-poetry/chutti-ke-din-hindi-poetry_cover.jpg",
  },
  {
    id: 23,
    title: "Jana Awjanar Majhe PB",
    slug: "jana-awjanar-majhe-pb", 
    publish_year: 2022,
    author: "Bimal Chakravarty",
    price: 195,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/jana-awjanar-majhe-pb/jana-awjanar-majhe-pb_cover.jpg",
  },
  {
    id: 24,
    title: "Jana Awjanar Majhe HB",
    slug: "jana-awjanar-majhe-hb",
    publish_year: 2022,
    author: "Bimal Chakravarty",
    price: 695,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/jana-awjanar-majhe-hb/jana-awjanar-majhe-hb_cover.jpg",
  },
  {
    id: 25,
    title: "Swayam Se Parichay",
    slug: "swayam-se-parichay",
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 195,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/swayam-se-parichay/swayam-se-parichay_cover.jpg",
  },
  {
    id: 26,
    title: "Swayam Ka Ghuspaithiya",
    slug: "swayam-ka-ghuspaithiya",
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/swayam-ka-ghuspaithiya/swayam-ka-ghuspaithiya_cover.jpg",
  },
  {
    id: 27,
    title: "There Was a Girl I Loved Once",  
    slug: "there-was-a-girl-i-loved-once",
    publish_year: 2022,
    author: "Pariksith Singh",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/there-was-a-girl-i-loved-once/there-was-a-girl-i-loved-once_cover.jpg",
  },
  {
    id: 28,
    title: "Hindutva : Origin Evolution and Future",
    slug: "hindutva-origin-evolution-and-future",
    publish_year: 2023,
    author: "Aravindan Neelakandan",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hindutva-origin-evolution-and-future/hindutva-origin-evolution-and-future_cover.jpg",
  },
  {
    id: 29,
    title: "Life of an Industani",  
    slug: "life-of-an-industani", 
    publish_year: 2023,
    author: "Shiv Kunal Verma",
    price: 995,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/life-of-an-industani/life-of-an-industani_cover.jpg",
  },
  {
    id: 30,
    title: "All Stray Dogs Go to Heaven PB",  
    slug: "all-stray-dogs-go-to-heaven-pb",
    publish_year: 2023,
    author: "Krishna Candeth",
    price: 695,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/all-stray-dogs-go-to-heaven-pb/all-stray-dogs-go-to-heaven-pb_cover.jpg",
  },
  {
    id: 31,
    title: "Grit to Glory",  
    slug: "grit-to-glory", 
    publish_year: 2023,
    author: "Brig B.S. Mehta",
    price: 895,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/grit-to-glory/grit-to-glory_cover.jpg",
  },
  {
    id: 32,
    title: "Bharat Ke Janjatiya Krantiveer-PB",  
    slug: "bharat-ke-janjatiya-krantiveer-pb", 
    publish_year: 2023,
    author: "Dhaval Patel",
    price: 395,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/bharat-ke-janjatiya-krantiveer-pb/bharat-ke-janjatiya-krantiveer-pb_cover.jpg",
  },
  {
    id: 33,
    title: "Bharat Ke Janjatiya Krantiveer-HB",  
    slug: "bharat-ke-janjatiya-krantiveer-hb",
    publish_year: 2023,
    author: "Dhaval Patel",
    price: 695,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/bharat-ke-janjatiya-krantiveer-hb/bharat-ke-janjatiya-krantiveer-hb_cover.jpg",
  },
  {
    id: 34,
    title: "The Battle for IITs",
    slug: "the-battle-for-iits",
    publish_year: 2023,
    author: "Rajiv Malhotra, Vijaya Viswanathan",
    price: 250,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-battle-for-iits/the-battle-for-iits_cover.jpg",
  },
  {
    id: 35,
    title: "Varna Jati Caste",
    slug: "varna-jati-caste", 
    publish_year: 2023,
    author: "Rajiv Malhotra, Vijaya Viswanathan",
    price: 250,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/varna-jati-caste/varna-jati-caste_cover.jpg",
  },
  {
    id: 36,
    title: "The Power of Future Machines",
    slug: "the-power-of-future-machines",  
    publish_year: 2023,
    author: ["Rajiv Malhotra", "T. N. Sudarshan" ,"Manogna Sastry"],
    price: 750,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-power-of-future-machines/the-power-of-future-machines_cover.jpg",
  },
  {
    id: 37,
    title: "Of Newtons and Apples",  
    slug: "of-newtons-and-apples",  
    publish_year: 2023,
    author: "ABHISHEK KUMAR",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/of-newtons-and-apples/of-newtons-and-apples_cover.jpg",
  },
  {
    id: 38,
    title: "Probashir Golpo (Bengali)",  
    slug: "probasir-golpo-bengali",  
    publish_year: 2023,
    author: "Bimal Chakravarty",
    price: 250,
    book_image: "https://m.media-amazon.com/images/I/71YHfXm0XwL._SY466_.jpg",
  },
  {
    id: 39,
    title: "Symbols and Parables",  
    slug: "symbols-and-parables",  
    publish_year: 2023,
    author: "Dr. Alok Pandey",
    price: 295,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/symbols-and-parables/symbols-and-parables_cover.jpg",
  },
  {
    id: 40,
    title: "Adhyatmikta",
    slug: "adhyatmikta",  
    publish_year: 2023,
    author: "Rajarshi Ranjan Nandy",
    price: 495,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/adyatmikta/adhyatmikta_cover.jpg",
  },
  {
    id: 41,
    title: "Building Beyond Infra",
    slug: "building-beyond-infra",  
    publish_year: 2023,
    author: "Akhilesh Srivastava",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/building-beyond-infra/building-beyond-infra_cover.jpeg",
  },
  {
    id: 42,
    title: "Purvyam",  
    slug: "purvyam",  
    publish_year: 2023,
    author: "Abhishek Talwar",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/purvyam/purvyam_cover.jpeg",
  },
  {
    id: 43,
    title: "Completing Vyasa’s Mahabharta",
    slug: "completing-vyasas-mahabharta", 
    publish_year: 2023,
    author: "Abhinav Agarwal",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/completing-vyasas-mahabharta/completing-vyasas-mahabharta_cover.jpg",
  },
  {
    id: 44,
    title: "Hindus in Hindu Rashtra (Eng)",  
    slug: "hindus-in-hindu-rashtra-eng",  
    publish_year: 2023,
    author: "Anand Ranganathan",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hindus-in-hindu-rashtra-eng/hindus-in-hindu-rashtra-eng_cover.jpg",
  },
  {
    id: 45,
    title: "Invaders and Infidels - Book 2",  
    slug: "invaders-and-infidels-book-2", 
    publish_year: 2023,
    author: "Sandeep Balakrishna",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/invaders-and-infidels-book-2/invaders-and-infidels-book-2_cover.jpg",
  },
  {
    id: 46,
    title: "Sobha Singh Artist",  
    slug: "sobha-singh-artist",  
    publish_year: 2023,
    author: "HIRDAY PAUL SINGH",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/sobha-singh-artist/sobha-singh-artist_cover.jpg",
  },
  {
    id: 47,
    title: "The Never-dying Fire",
    slug: "the-never-dying-fire",  
    publish_year: 2023,
    author: "Luc Venet",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-never-dying-fire/the-never-dying-fire_cover.jpg",
  },
  {
    id: 48,
    title: "The Veda Made Simple",
    slug: "the-veda-made-simple",  
    publish_year: 2023,
    author: "Dr. Pariksith Singh",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-veda-made-simple/the-veda-made-simple_cover.jpg",
  },
  {
    id: 49,
    title: "Modi Ka Banaras",  
    slug: "modi-ka-banaras",  
    publish_year: 2023,
    author: "Arvind Chaturvedi",
    price: 449,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/modi-ka-banaras/modi-ka-banaras_cover.jpg",
  },
  {
    id: 50,
    title: "India and the Changing World Order",
    slug: "india-and-the-changing-world-order",  
    publish_year: 2023,
    author: "S. Gurumurthy",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/india-and-the-changing-world-order/india-and-the-changing-world-order_cover.jpg",
  },
  {
    id: 51,
    title: "Gods Dancing Among Men",
    slug: "gods-dancing-among-men",  
    publish_year: 2023,
    author: "PUSHPA KURUP",
    price: 1999,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/gods-dancing-among-men/gods-dancing-among-men_cover.jpg",
  },
  {
    id: 52,
    title: "Arc of Governance",
    slug: "arc-of-governance",  
    publish_year: 2023,
    author: "M.G. Devasahayam",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/arc-of-governance/arc-of-governance_cover.jpg",
  },
  {
    id: 53,
    title: "Hindus in Hindu Rashtra (Hindi)",  
    slug: "hindus-in-hindu-rashtra-hindi",  
    publish_year: 2023,
    author: "Anand Ranganathan",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hindus-in-hindu-rashtra-hindi/hindus-in-hindu-rashtra-hindi_cover.jpg",
  },
  {
    id: 54,
    title: "Hindus in Hindu Rashtra (Marathi)",  
    slug: "hindus-in-hindu-rashtra-marathi",
    publish_year: 2023,
    author: "Anand Ranganathan",
    price: 350,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/hindus-in-hindu-rashtra-marathi/hindus-in-hindu-rashtra-marathi_cover.jpg",
  },
  {
    id: 55,
    title: "The Vaccine War",
    slug: "the-vaccine-war", 
    publish_year: 2023,
    author: "Vivek Ranjan Agnihotri",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-vaccine-war/the-vaccine-war_cover.jpg",
  },
  {
    id: 56,
    title: "Ram Janmabhoomi",
    slug: "ram-janmabhoomi",  
    publish_year: 2024,
    author: "Rashmi Samant",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/ram-janmabhoomi/ram-janmabhoomi_cover.jpg",
  },
  {
    id: 57,
    title: "Modis Governance Triump",
    slug: "modis-governance-triump",  
    publish_year: 2024,
    author: "Tarun Chugh",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/modis-governance-triump/modis-governance-triump_cover.jpg",
  },
  {
    id: 58,
    title: "Compulsive Nose-Picking and Other True Tales",
    slug: "compulsive-nose-picking-and-other-true-tales",  
    publish_year: 2024,
    author: "Anil Maheshwari",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/compulsive-nose-picking-and-other-true-tales/compulsive-nose-picking-and-other-true-tales_cover.jpg",
  },
  {
    id: 59,
    title: "Waiting for Shiva",
    slug: "waiting-for-shiva",  
    publish_year: 2024,
    author: "Vikram Sampath",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/waiting-for-shiva/waiting-for-shiva_cover.jpg",
  },
  {
    id: 60,
    title: "Snakes in the Ganga (PB)",  
    slug: "snakes-in-the-ganga-pb",  
    publish_year: 2024,
    author: "Rajiv Malhotra",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/snakes-in-the-ganga/snakes-in-the-ganga_cover.jpg",
  },
  {
    id: 61,
    title: "Modian Consensus",
    slug: "modian-consensus",  
    publish_year: 2024,
    author: "Swadesh Singh",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/modian-consensus/modian-consensus_cover.jpg",
  },
  {
    id: 62,
    title: "Bharat Rising",  
    slug: "bharat-rising",  
    publish_year: 2024,
    author: "Utpal Kumar",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/bharat-rising/bharat-rising_cover.jpg",
  },
  {
    id: 63,
    title: "Ram Janmabhoomi (Hindi)",
    slug: "ram-janmabhoomi-hindi", 
    publish_year: 2024,
    author: "Rashmi Samant",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/ram-janmabhoomi-hindi/ram-janmabhoomi-hindi_cover.jpg",
  },
  {
    id: 64,
    title: "Whispers of the Unseen",
    slug: "whispers-of-the-unseen", 
    publish_year: 2024,
    author: "S Beena Unikrishnan",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/whispers-of-the-unseen/whispers-of-the-unseen_cover.jpg",
  },
  {
    id: 65,
    title: "Adideva",  
    slug: "adideva",  
    publish_year: 2024,
    author: "DEEPA BHASKARAN SALEM",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/adideva/adideva_cover.jpg",
  },
  {
    id: 66,
    title: "Modi's Governance Triumph (Hindi)",
    slug: "modis-governance-triumph-hindi",  
    publish_year: 2024,
    author: "Tarun Chugh",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/modis-governance-triumph-hindi/modis-governance-triumph-hindi_cover.webp",
  },
  {
    id: 67,
    title: "Invaders and Infidels - Book 1",  
    slug: "invaders-and-infidels-book-1",  
    publish_year: 2024,
    author: "Sandeep Balakrishna",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/invaders-and-infidels-book-1/invaders-and-infidels-book-1_cover.jpg",
  },
  {
    id: 68,
    title: "Nastik",  
    slug: "nastik", 
    publish_year: 2024,
    author: "KUSHAL MEHRA",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/nastik/nastik_cover.jpg",
  },
  {
    id: 69,
    title: "Waiting For Shiva (Hindi)",
    slug: "waiting-for-shiva-hindi", 
    publish_year: 2024,
    author: "Vikram Sampath",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/waiting-for-shiva-hindi/waiting-for-shiva-hindi_cover.jpg",
  },
  {
    id: 70,
    title: "Apostles",  
    slug: "apostles",  
    publish_year: 2024,
    author: "Biswaroop Mukherjee",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/apostles/apostles_cover.jpg",
  },
  {
    id: 71,
    title: "Devdoot (Hindi)",
    slug: "devdoot-hindi",  
    publish_year: 2024,
    author: "Aniruddh Rawat",
    price: 199,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/devdoot-hindi/devdoot-hindi_cover.jpg",
  },
  {
    id: 72,
    title: "Stalled Wheels of Justice",
    slug: "stalled-wheels-of-justice", 
    publish_year: 2024,
    author: "Shishir Tripathi",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/stalled-wheels-of-justice/stalled-wheels-of-justice_cover.jpg",
  },
  {
    id: 73,
    title: "Bangaliyana",
    slug: "bangaliyana", 
    publish_year: 2024,
    author: "Rajeev Banerjee",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/bangaliyana/bangaliyana_cover.jpg",
  },
  {
    id: 74,
    title: "Waiting For Shiva (Marathi)",
    slug: "waiting-for-shiva-marathi", 
    publish_year: 2024,
    author: "Vikram Sampath",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/waiting-for-shiva-marathi/waiting-for-shiva-marathi_cover.jpg",
  },
  {
    id: 75,
    title: "Krishna Niti",
    slug: "krishna-niti",  
    publish_year: 2024,
    author: ["Kushagra Aniket", "Nityananda Misra"],
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/krishna-niti/krishna-niti_cover.jpg",
  },
  {
    id: 76,
    title: "Whispers from the Past",  
    slug: "whispers-from-the-past",  
    publish_year: 2024,
    author: "Subhash Kak",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/whispers-from-the-past/whispers-from-the-past_cover.jpg",
  },
  {
    id: 77,
    title: "Kashi",  
    slug: "kashi",  
    publish_year: 2024,
    author: "Aditi Banerjee",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/kashi/kashi_cover.jpg",
  },
  {
    id: 78,
    title: "My Freedom of Expression",
    slug: "my-freedom-of-expression",  
    publish_year: 2024,
    author: "PARIMAL BRAHMA",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/my-freedom-of-expression/my-freedom-of-expression_cover.jpg",
  },
  {
    id: 79,
    title: "Shared Roots",
    slug: "shared-roots", 
    publish_year: 2024,
    author: "Ratul Chakraborty",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/shared-roots/shared-roots_cover.jpg",
  },
  {
    id: 80,
    title: "Reclaiming Bharatvarsha",
    slug: "reclaiming-bharatvarsha", 
    publish_year: 2024,
    author: "Sandeep Balakrishna",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/reclaiming-bharatvarsha/reclaiming-bharatvarsha_cover.jpg",
  },
  {
    id: 81,
    title: "Rearming Hinduism",  
    slug: "rearming-hinduism",  
    publish_year: 2024,
    author: "Vamsee Juluri",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/rearming-hinduism/rearming-hinduism_cover.jpg",
  },
  {
    id: 82,
    title: "Desire, Dreams and Powers",
    slug: "desire-dreams-and-powers",  
    publish_year: 2024,
    author: "TATHAGATA ROY",
    price: 899,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/desire-dreams-and-powers/desire-dreams-and-powers_cover.jpg",
  },
  {
    id: 83,
    title: "The Collector's Mother",
    slug: "the-collectors-mother",  
    publish_year: 2024,
    author: "Bishnupada Sethi",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-collectors-mother/the-collectors-mother_cover.jpg",
  },
  {
    id: 84,
    title: "How to Get into IAS",  
    slug: "how-to-get-into-ias",  
    publish_year: 2024,
    author: "Rohit Sharma & Shakti Singh (IRS)",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/how-to-get-into-ias/how-to-get-into-ias_cover.jpg",
  },
  {
    id: 85,
    title: "Decolonizing Hinduism",
    slug: "decolonizing-hinduism",  
    publish_year: 2024,
    author: "Shubham G. Deore",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/decolonizing-hinduism/decolonizing-hinduism_cover.jpg",
  },
  {
    id: 86,
    title: "The Battle for Consciousness Theory: A Response to Ken Wilber's Hijacking of Sri Aurobindo and Other Indian Thought",  
    slug: "the-battle-for-consciousness-theory-a-response-to-ken-wilbers-hijacking-of-sri-aurobindo-and-other-indian-thought",  
    publish_year: 2024,
    author: ["Rajiv Malhotra", " Manogna Sastry", " Kundan Singh"],
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-battle-for-consciousness-theory-a-response-to-ken-wilbers-hijacking-of-sri-aurobindo-and-other-indian-thought/the-battle-for-consciousness-theory-a-response-to-ken-wilbers-hijacking-of-sri-aurobindo-and-other-indian-thought_cover.jpg",
  },
  {
    id: 87,
    title: "India in 2050: Visions for a Superpower India",
    slug: "india-in-2050-visions-for-a-superpower-india",
    publish_year: 2024,
    author: "Karan Mehrishi",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/india-in-2050-visions-for-a-superpower-india/india-in-2050-visions-for-a-superpower-india_cover.jpg",
  },
  {
    id: 88,
    title: "Being Hindu",
    slug: "being-hindu", 
    publish_year: 2024,
    author: "Saumya Dey",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/being-hindu/being-hindu_cover.jpg",
  },
  {
    id: 89,
    title: "Waiting for Shiva (Telugu)",
    slug: "waiting-for-shiva-telugu",  
    publish_year: 2024,
    author: "Vikram Sampath",
    price: 499,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/waiting-for-shiva-telugu/waiting-for-shiva-telugu_cover.jpg",
},
  {
    id: 90,
    title: "Genome to Om",
    slug: "genome-to-om",  
    publish_year: 2024,
    author: ["Bhushan Patwardhan", "Indu Ramchandani"],
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/genome-to-om/genome-to-om_cover.jpg",
  },
  {
    id: 91,
    title: "The Number you are Calling is Switched off",  
    slug: "the-number-you-are-calling-is-switched-off",  
    publish_year: 2024,
    author: "Tushar Srivastava",
    price: 399,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/the-number-you-are-calling-is-switched-off/the-number-you-are-calling-is-switched-off_cover.jpg",
  },
  {
    id: 92,
    title: "Crossing Continents: European Explorers and India's Mysteries",  
    slug: "crossing-continents-european-explorers-and-indias-mysteries",  
    publish_year: 2024,
    author: "Amit Agarwal",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/crossing-continents-european-explorers-and-indias-mysteries/crossing-continents-european-explorers-and-indias-mysteries_cover.jpg",
  },
  {
    id: 93,
    title: "From Partition to Progress: Persecuted Hindus and the Struggle for Citizenship",  
    slug: "from-partition-to-progress-persecuted-hindus-and-the-struggle-for-citizenship",  
    publish_year: 2024,
    author: "Anirban Ganguly",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/from-partition-to-progress-persecuted-hindus-and-the-struggle-for-citizenship/from-partition-to-progress-persecuted-hindus-and-the-struggle-for-citizenship_cover.jpg",
  },
  {
    id: 94,
    title: "India's New Right: Powering the Current Wave of Nationalism and Civilisational Revival",  
    slug: "indias-new-right-powering-the-current-wave-of-nationalism-and-civilisational-revival", 
    publish_year: 2024,
    author: "Abhijit Majumder",
    price: 699,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/indias-new-right-powering-the-current-wave-of-nationalism-and-civilisational-revival/indias-new-right-powering-the-current-wave-of-nationalism-and-civilisational-revival_cover.jpg",
  },
  {
    id: 95,
    title: "A Dharmic Social History of India",
    slug: "a-dharmic-social-history-of-india",  
    publish_year: 2024,
    author: "Aravindan Neelakandan",
    price: 799,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/a-dharmic-social-history-of-india/a-dharmic-social-history-of-india_cover.jpg",
  },
  {
    id: 96,
    title: "Padma Bharatis",
    slug: "padma-bharatis",
    publish_year: 2024,
    author: "Jay Jina",
    price: 599,
    book_image: "https://bluone-ink.s3.amazonaws.com/images/books/padma-bharatis/padma-bharatis_cover.jpg",
  },
  ];