export const allGalleryList = [
  {
    "id": 1,
    "title": "Nastik: Why I Am Not an Atheist",
    "galleryslug": "nastik-why-i-am-not-an-atheist",
    "gallerydate": "2024-05-09",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_0268.JPG",
    "gallerydescription": "On May 9, 2024, we gathered for the exciting launch of Kushal Mehra's Nastik, featuring esteemed panelists Dr. Anand Ranganathan and Abhijit Iyer Mitra, moderated by Shambhav Sharma.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_0152.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_0136.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_0141.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_0150.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_0268.JPG", 
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_0197.PNG",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_0161.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Nastik+Book+Launch/IMG_1613.webp",
    ],
  },
  {
    "id": 2,
    "title": "Rearming Hinduism: Nature, Hinduphobia, and the Return of Indian Intelligence",
    "galleryslug": "rearming-hinduism-nature-hinduphobia-and-the-return-of-indian-intelligence",
    "gallerydate": "2024-06-14",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Rearming+Hinduism+Launch/IMG_0750.JPG",
    "gallerydescription": "On June 14, 2024, we celebrated the launch of Vamsee Juluri's Rearming Hinduism, featuring dynamic discussions with Dr. Anand Ranganathan and Adv. J. Sai Deepak, expertly moderated by Ashish Dhar.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Rearming+Hinduism+Launch/IMG_0751.JPG",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Rearming+Hinduism+Launch/IMG_0750.JPG", 
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Rearming+Hinduism+Launch/IMG_0728.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Rearming+Hinduism+Launch/IMG_0730.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Rearming+Hinduism+Launch/IMG_0716.webp",
      
    ],
  },
  {
    "id": 3,
    "title": "Genome to Om: Evolving Journey of Modern Science to Meta-science",
    "galleryslug": "genome-to-om-evolving-journey-of-modern-science-to-meta-science",
    "gallerydate": "2024-09-11",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Genome+to+Om+launch/IMG_2055.webp",
    "gallerydescription": "The launch of Genome to Om by Dr. Bhushan Patwardhan and Indu Ramchandani on September 11, 2024, brought together an esteemed panel of experts: Dr. Anil Sahasrabuddhe, Dr. BN Gangadhar, Dr. K.K. Agarwal, Dr. Pankaj Mittal, and Dr. Haritma Chopra.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Genome+to+Om+launch/IMG_2070.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Genome+to+Om+launch/IMG_2055.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Genome+to+Om+launch/IMG_2138.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Genome+to+Om+launch/IMG_2096.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Genome+to+Om+launch/IMG_2088.webp", 
    ],
  },
  {
    "id": 4,
    "title": "Waiting for Shiva: Unearthing the Truth of Kashi’s Gyan Vapi",
    "galleryslug": "waiting-for-shiva-unearthing-the-truth-of-kashis-gyan-vapi",
    "gallerydate": "2024-03-04",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Waiting+For+Shiva+Launch/DSC07227+(1).webp",
    "gallerydescription": "Launched on March 4, 2024, Waiting for Shiva, authored by Dr Vikram Sampath, featured the Honourable Finance Minister Smt. Nirmala Sitharaman as the chief guest, alongside esteemed panelists Dr. Anand Ranganathan and Adv. Vishnu Shankar Jain, moderated by Advaita Kala.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Waiting+For+Shiva+Launch/DSC06954+(1).webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Waiting+For+Shiva+Launch/DSC07123+(2).webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Waiting+For+Shiva+Launch/DSC07127+(2).webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Waiting+For+Shiva+Launch/DSC07227+(1).webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Waiting+For+Shiva+Launch/DSC06811+(4).webp", 
    ],
  },
  {
    "id": 5,
    "title": "My Freedom of Expression: Reflections on Contemporary Issues",
    "galleryslug": "my-freedom-of-expression-reflections-on-contemporary-issues",
    "gallerydate": "2024-08-10",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/My+Freedom+of+Expression+Launch/569bca15-7528-4dbb-a66e-693941c44620.jpg",
    "gallerydescription": "On August 10, 2024, we celebrated the launch of My Freedom of Expression by Parimal Brahma, chaired by the esteemed Dr. Bibek Debroy. The event featured insightful discussions from speakers Sh. Ravindra Kumar, Sh. Amitabha Bhattacharya, and Sh. Jay Bhattacharjee, fostering a rich dialogue on contemporary issues.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/My+Freedom+of+Expression+Launch/569bca15-7528-4dbb-a66e-693941c44620.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/My+Freedom+of+Expression+Launch/b3772e37-48c1-4379-8aab-ca881592937f.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/My+Freedom+of+Expression+Launch/b3772e37-48c1-4379-8aab-ca881592937f.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/My+Freedom+of+Expression+Launch/f2ba6a0d-8303-4eed-9d6e-4d02db29d8f1.jpg",
    ],
  },
  {
    "id": 6,
    "title": "This is Sanatan Dharma: The Quest for Truth",
    "galleryslug": "this-is-sanatan-dharma-the-quest-for-truth",
    "gallerydate": "2024-08-17",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/This+is+Sanatan+Dharma/img1.jpg",
    "gallerydescription": "On August 17, 2023, the launch of This is Sanatan Dharma: The Quest for Truth brought together an engaging discussion at Vivekananda International Foundation, New Delhi. The event featured the author, Partho, in conversation with Swami Paramatmananda, Dr. Anirban Ganguly, and Dr. Arvind Gupta. Together, they delved into the profound themes of Sanatan Dharma and its contemporary relevance, offering the audience a captivating glimpse into the book’s exploration of eternal truths.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/This+is+Sanatan+Dharma/img1.jpg",
    ],
  },
  {
    "id": 7,
    "title": "Bharat Ke Janjaatiya Krantiveer",
    "galleryslug": "bharat-ke-janjaatiya-krantiveer",
    "gallerydate": "2023-03-21",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Bharat+Ke+Janjatiya+Krantiveer/img2.jpg",
    "gallerydescription": "Sri Dhaval Patel, the author of Bharat Ke Janjaatiya Krantiveer, had the honor of meeting the Honourable Prime Minister of India, Sri Narendra Modi Ji. During this special occasion, the Prime Minister signed the latest copy of the book and extended his best regards to the author, recognizing the significance of this important work.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Bharat+Ke+Janjatiya+Krantiveer/img1.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Bharat+Ke+Janjatiya+Krantiveer/img2.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Bharat+Ke+Janjatiya+Krantiveer/img3.jpg",
    ],
  },
  {
    "id": 8,
    "title": "Pondy Lit Fest",
    "galleryslug": "pondy-lit-fest",
    "gallerydate": "2023-09-15",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Pondy+Lit+Fest/img4.jpg",
    "gallerydescription": "From September 15-17, 2023, the Pondy Literature Festival brought together a vibrant community of authors, readers, and intellectuals. The event showcased a series of insightful book launches and engaging discussions, featuring prominent authors such as Partho, Dr. Pariksith Singh, Sandeep Balakrishna, Abhinav Agarwal, and Luc Venet. Their thought-provoking talks offered unique perspectives on various contemporary issues, making the festival an enriching experience for all.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Pondy+Lit+Fest/img1.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Pondy+Lit+Fest/img2.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Pondy+Lit+Fest/img3.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Pondy+Lit+Fest/img4.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Pondy+Lit+Fest/img5.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Pondy+Lit+Fest/img6.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Pondy+Lit+Fest/img7.jpg",
    ],
  },
  {
    "id": 9,
    "title": "Jaipur Literature Festival",
    "galleryslug": "jaipur-literature-festival",
    "gallerydate": "2023-01-19",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Jaipur+Lit+Fest/327041832_6095855113834032_7776145733048426105_n.jpg",
    "gallerydescription": "From January 19-23, 2023, the Jaipur Literature Festival was hosted at Hotel Clarks Amer, Jaipur, bringing together authors, readers, and intellectuals for an enriching literary experience. The event featured insightful sessions with celebrated authors such as Partho, Dr. Pariksith Singh, and Shiv Kunal Verma. Through engaging discussions and thought-provoking dialogues, the festival celebrated the power of stories and ideas, leaving a lasting impression on all attendees.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Jaipur+Lit+Fest/327041832_6095855113834032_7776145733048426105_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Jaipur+Lit+Fest/326674130_695962655270279_4317650604851790560_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Jaipur+Lit+Fest/326787500_728600295334846_7617561087655929394_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Jaipur+Lit+Fest/326927663_2463442713811663_6161537497082112794_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Jaipur+Lit+Fest/326950595_2333346563492708_6287865546343122978_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Jaipur+Lit+Fest/327041832_6095855113834032_7776145733048426105_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Jaipur+Lit+Fest/327071075_5577954318998686_230295029604938010_n.jpg",
    ],
  },
  {
    "id": 10,
    "title": "Life of an Industani",
    "galleryslug": "life-of-an-industani",
    "gallerydate": "2022-12-23",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Life+of+an+Industani/320340357_3426598424228123_5874316674092449965_n.jpg",
    "gallerydescription": "The Fireside Chat on Life of an Industani brought together an engaging discussion on critical contemporary events. The session featured thought-provoking insights from Dr. Bibek Debroy, General Vijay Kumar Singh (PVSM, AVSM, YSM, ADC), Lt. Gen Rakesh Kumar Loomba (PVSM, AVSM), and the author Shiv Kunal Verma, who is also a renowned photographer and filmmaker. The event offered a unique perspective on modern India through the lens of this compelling book.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Life+of+an+Industani/319691643_508245521122987_8672984504033886246_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Life+of+an+Industani/320340357_3426598424228123_5874316674092449965_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Life+of+an+Industani/320065085_494515802670828_892105772737453311_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Life+of+an+Industani/319944531_884174132997514_3501897817061520022_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Life+of+an+Industani/320717310_563970938455940_8393736159683076896_n.jpg",
    ],
  },
  {
    "id": 11,
    "title": "Hindutva: Origin, Evolution, and Future",
    "galleryslug": "hindutva-origin-evolution-and-future",
    "gallerydate": "2022-12-02",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Hindutva/317979219_517551073728268_8066983291769481732_n.jpg",
    "gallerydescription": "On December 2, 2022, the launch of Hindutva: Origin, Evolution, and Future by Sri Aravindan Neelakandan took place at the Constitution Club of India, New Delhi. The event featured a dynamic panel discussion with Sri K Annamalai, Sri Tejasvi Surya, Sri Abhinav Prakash, and Sri Makarand Paranjape. Together, they explored the book’s deep insights into the historical roots, development, and future trajectory of Hindutva, offering the audience a thought-provoking and enriching experience.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Hindutva/318032882_517617453721630_5693562280853539691_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Hindutva/317979219_517551073728268_8066983291769481732_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Hindutva/318047633_517551063728269_7557615465139069566_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Hindutva/318086611_517617457054963_5035169914980051217_n.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Hindutva/318116193_517617450388297_551903669424026902_n.jpg",
    ],
  },
  {
    "id": 12,
    "title": "Snakes in the Ganga: Breaking India 2.0",
    "galleryslug": "snakes-in-the-ganga-breaking-india-2.0",
    "gallerydate": "2022-09-27",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Snakes+in+the+Ganga/308735341_517612300371264_7789911507720721013_n.webp",
    "gallerydescription": "Snakes in the Ganga: Breaking India 2.0 by best-selling authors Rajiv Malhotra and Vijaya Viswanathan was officially launched amidst much anticipation and excitement. This path-breaking book has garnered critical acclaim from prominent academicians such as Prof. Peter Boghossian and Prof. R. Vaidyanathan for its bold insights and thorough research. The event offered a glimpse into the powerful ideas that challenge conventional narratives and delve into issues shaping India’s future.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Snakes+in+the+Ganga/309466307_517612257037935_3161392970222036632_n.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Snakes+in+the+Ganga/308446650_517612190371275_8242176327115849384_n.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Snakes+in+the+Ganga/308550606_517612213704606_2554012480603801470_n.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Snakes+in+the+Ganga/308735341_517612300371264_7789911507720721013_n.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Snakes+in+the+Ganga/309537817_517612187037942_6621960525635632694_n+(1).webp",
    ],
  },
  {
    "id": 13,
    "title": "Becoming the Storm",
    "galleryslug": "becoming-the-storm",
    "gallerydate": "2024-12-09",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Becoming+the+Storm/IMG_3684.webp",
    "gallerydescription": "The Book Discussion Programme on Becoming the Storm by Rami Chhabra took place on December 9, 2024, at 6:00 PM at the C.D. Deshmukh Auditorium, India International Centre, New Delhi. The event featured an engaging panel discussion with Shashi Tharoor (Member of Parliament & Eminent Author) and Veena Sikri (Former Diplomat & Convener, South Asia Women’s Network). The evening was further enriched by a dramatic reading of excerpts performed by Living Room Theatre Artists and a soulful musical overture by V.P. Mishra, offering the audience a memorable and thought-provoking experience.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Becoming+the+Storm/IMG_3651.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Becoming+the+Storm/IMG_3643.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Becoming+the+Storm/IMG_3684.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Becoming+the+Storm/IMG_3752.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Becoming+the+Storm/IMG_3777.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Becoming+the+Storm/IMG_3785.webp",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/Becoming+the+Storm/IMG_3790.jpg",
    ],
  },
  {
    "id": 14,
    "title": "The Nukes, the Jihad, the Hawalas and Crystal Meth",
    "galleryslug": "the-nukes-the-jihad-the-hawalas-and-crystal-meth",
    "gallerydate": "2024-12-11",
    "galleryimage": "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/The+Nukes%2C+the+Jihad%2C+the+Hawalas+and+Crystal+Meth+/1.jpg",
    "gallerydescription": "The Book Signing & Meet and Greet event for The Nukes, the Jihad, the Hawalas and Crystal Meth by Iqbal Chand Malhotra took place at Connaught Place and Khan Market, New Delhi, on December 11 and 12, 2024. The event provided readers with a unique opportunity to meet the author, have their copies signed, and engage in insightful conversations about the book’s riveting exploration of its themes.",
    "galleryimages": [
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/The+Nukes%2C+the+Jihad%2C+the+Hawalas+and+Crystal+Meth+/1.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/The+Nukes%2C+the+Jihad%2C+the+Hawalas+and+Crystal+Meth+/2.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/The+Nukes%2C+the+Jihad%2C+the+Hawalas+and+Crystal+Meth+/3.jpg",
      "https://bluone-ink.s3.us-east-1.amazonaws.com/images/Gallery/The+Nukes%2C+the+Jihad%2C+the+Hawalas+and+Crystal+Meth+/4.jpg",
    ],
  },
];
